spring.application.name=ms-gateway
server.port=8091

spring.cloud.gateway.server.webmvc.routes[0].id=ms-auth
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://ms-auth
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=ms-facturacion-y-presupuesto
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://ms-facturacion-y-presupuesto
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/facturacio-y-presupuesto/**

spring.cloud.gateway.server.webmvc.routes[2].id=ms-ficha-medica
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://ms-ficha-medica
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/fichas_medicas/**

spring.cloud.gateway.server.webmvc.routes[3].id=ms-medico
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://ms-medico
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=api/v1/medicos/**

spring.cloud.gateway.server.webmvc.routes[4].id=ms-opinion-del-paciente
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://ms-opinion-del-paciente
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/v1/opiniones/**

spring.cloud.gateway.server.webmvc.routes[5].id=ms-paciente
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://ms-paciente
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/v1/pacientes/**

spring.cloud.gateway.server.webmvc.routes[6].id=ms-pagos
spring.cloud.gateway.server.webmvc.routes[6].uri=lb://ms-pagos
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/api/v1/pagos/**

spring.cloud.gateway.server.webmvc.routes[7].id=ms-receta-medica
spring.cloud.gateway.server.webmvc.routes[7].uri=lb://ms-receta-medica
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/api/v1/recetasMedicas/**

spring.cloud.gateway.server.webmvc.routes[8].id=ms-registro-de-materiales
spring.cloud.gateway.server.webmvc.routes[8].uri=lb://ms-registro-de-materiales
spring.cloud.gateway.server.webmvc.routes[8].predicates[0]=Path=/api/v1/registrosMateriales/**

spring.cloud.gateway.server.webmvc.routes[9].id=ms-registros-de-atenciones
spring.cloud.gateway.server.webmvc.routes[9].uri=lb://ms-registros-de-atenciones
spring.cloud.gateway.server.webmvc.routes[9].predicates[0]=Path=/api/v1/registro-atenciones/**

spring.cloud.gateway.server.webmvc.routes[10].id=ms-reservar-y-anular-hora
spring.cloud.gateway.server.webmvc.routes[10].uri=lb://ms-reservar-y-anular-hora
spring.cloud.gateway.server.webmvc.routes[10].predicates[0]=Path=/api/v1/reservar-y-anular-hora/**
# Eureka Client
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
