spring.application.name=ms-reservar-y-anular-hora

server.port=8090

spring.datasource.url=jdbc:mysql://localhost:3306/ms_reservar_y_anular_hora
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.flyway.enabled=true

jwt.secret=clave_super_secreta_12345678912345678900